yum_repos:
    zfs-kmod:
        name: ZFS on Linux for EL7 - kmod
        baseurl: http://download.zfsonlinux.org/epel/7.8/kmod/$basearch/
        enabled: true
        metadata_expire: 7d
        gpgcheck: false

packages:
  - squid
  - mariadb-server
  - ipa-server-dns
  - jq
  - zfs

runcmd:
  # rsyslog
  - sed -i '/^#$ModLoad imtcp$/s/^#//' /etc/rsyslog.conf
  - sed -i '/^#$InputTCPServerRun 514$/s/^#//' /etc/rsyslog.conf
  - systemctl restart rsyslog
  # Squid
  - systemctl start squid
  - systemctl enable squid
  # Shared folders
  - mkdir /scratch
  - mkdir -p /project
  # NFS
  - systemctl enable rpcbind
  - systemctl enable nfs-server
  - systemctl start rpcbind
  - systemctl start nfs-server
  # Slurm ctld and bd
  - yum install -y slurm-slurmdbd slurm-slurmctld
  - systemctl enable slurmctld
  - systemctl start  slurmctld
  ## ZFS 
  #- /sbin/modprobe zfs
  #- zpool create genetic vdb
  #- zfs create genetic/projects -o mountpoint=/export/projects sharenfs=on compression=on 
  - bash /root/zfs_set.sh

write_files:
  - path: /root/zfs_set.sh 
    permission: 700
    content: |
      #!/bin/bash
      /sbin/modprobe zfs
      pool=genetic
      name=projects
      mnt_pt=/export/$name
      fs=$pool/$name
      # the device is hard coded in the terraform script
      device=/dev/vdb
      zpool create $pool $device
      zfs create -o mountpoint=$mnt_pt -o sharenfs=on -o compression=on $fs
  - path: /root/freeipa.sh
    permissions: 0700
    content: |
        #!/bin/bash
        set -e
        DOMAIN="${domain_name}"
        REALM=$${DOMAIN^^}
        hostnamectl set-hostname mgmt01.$DOMAIN
        LOCAL_IP=$(ifconfig eth0 | grep -P -o 'inet \K\S+')
        # GCP automatically add an entry for this IP. It must be removed to avoid conflict with ipa-server
        sed -i "/$LOCAL_IP/d" /etc/hosts 
        ipa-server-install --hostname mgmt01.$DOMAIN --setup-dns \
                           --ds-password ${admin_passwd} --admin-password ${admin_passwd} \
                           --mkhomedir --ssh-trust-dns --unattended \
                           --auto-forwarders \
                           --ip-address=$LOCAL_IP \
                           --no-host-dns --no-dnssec-validation --realm=$REALM
        # Configure password for guest accounts
        echo "${admin_passwd}" | kinit admin
        ipa pwpolicy-mod  --minlife=0
        for i in $(seq -f "%02g" 1 ${nb_users}); do
            echo ${guest_passwd} | ipa user-add user$i --first user --last $i --email user$i@example.com --shell /bin/bash --password
        done
        kdestroy
        for i in $(seq -f "%02g" 1 ${nb_users}); do
            echo -e "${guest_passwd}\n${guest_passwd}\n${guest_passwd}" | kinit user$i
            kdestroy
        done
        # create home directories
        for i in $(seq -f "%02g" 1 ${nb_users}); do
            mkhomedir_helper user$i
        done
  - content: |
        /home          ${cidr}(rw,sync,no_root_squash,no_all_squash)
        /project       ${cidr}(rw,sync,no_root_squash,no_all_squash)
        /scratch       ${cidr}(rw,sync,no_root_squash,no_all_squash)
        /etc/slurm     ${cidr}(rw,sync,no_root_squash,no_all_squash)
    path: /etc/exports
  - content: |
        acl SSL_ports port 443
        acl Safe_ports port 80
        acl Safe_ports port 443
        acl Safe_ports port 1025-65535
        acl CONNECT method CONNECT

        # predefined http_accesses
        http_access allow manager localhost
        http_access deny manager
        http_access deny !Safe_ports
        http_access deny CONNECT !SSL_ports

        # user-defined ACLs
        acl compute_network src ${cidr}
        acl compute_dstdom_regex dstdom_regex ^(cvmfs-.*\.computecanada\.ca)$

        # user-defined http_accesses
        http_access allow compute_network compute_dstdom_regex
        http_access allow localhost
        http_access deny all

        # user-defined http_port
        http_port 3128

        # general settings
        coredump_dir                   /var/spool/squid
        maximum_object_size_in_memory  512 KB
        maximum_object_size            4096 KB
        cache_mgr                      root
        client_persistent_connections  on
        server_persistent_connections  on
        forwarded_for                  on
        via                            on
        access_log                     /var/log/squid/access.log

        cache_mem                      256 MB
        cache_store_log                /var/log/squid/store.log
        cache_log                      /var/log/squid/cache.log

        refresh_pattern /cvmfs/soft.computecanada.ca/.cvmfs*          	0  100%	30
        refresh_pattern /cvmfs/soft.computecanada.ca/data/*   	525600  100%	525600 
        refresh_pattern                .                     0    20%     4320

        cache_dir ufs /var/spool/squid 4096 16 256
    path: /etc/squid/squid.conf
